name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      content: read
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - run: mise publish
